# Generated by Django 5.2.5 on 2025-10-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(choices=[('inventario', 'Inventario'), ('compras', 'Compras y Proveedores'), ('produccion', 'Producción'), ('ventas', 'Ventas y Clientes'), ('costos', 'Costos y Finanzas')], unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Clase CSS para icono', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos del Sistema',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rol',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, help_text='Área de trabajo: Producción, Ventas, Finanzas, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del rol')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol del Sistema',
                'verbose_name_plural': 'Roles del Sistema',
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='Ver')),
                ('can_add', models.BooleanField(default=False, verbose_name='Crear')),
                ('can_change', models.BooleanField(default=False, verbose_name='Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_perms', to='accounts.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_perms', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Permiso Rol-Módulo',
                'verbose_name_plural': 'Permisos Rol-Módulo',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
