# Generated by Django 5.2.5 on 2025-10-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_module_alter_userprofile_options_and_more'),
        ('accounts', '0002_userprofile_id_usuario'),
    ]

    operations = [
    ]
