# Generated by Django 5.2.5 on 2025-10-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_id_usuario'),
        ('inventario', '0002_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
    ]
