# Generated by Django 5.2.5 on 2025-10-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20251009_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_usuario',
        ),
    ]
