# Generated by Django 5.2.5 on 2025-10-03 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_oc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProductos',
            fields=[
                ('id_orden_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pedidos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pedidos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOC',
            fields=[
                ('id_detalle_oc', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.usuario'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.usuario'),
        ),
    ]
