# Generated by Django 5.2.5 on 2025-10-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bodega',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.TextField(default='Sin ubicación definida'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
