# Generated by Django 5.2.5 on 2025-10-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_create_at_bodega_created_at_bodega_capacidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
