# Generated by Django 5.2.5 on 2025-10-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_proveedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra'),
        ),
    ]
